# Use the official Apache image
FROM httpd:2.4

# Copy your HTML directory into the default web root
COPY ./dist/ /usr/local/apache2/htdocs/

# Expose port 80 (optional, mostly for documentation purposes)
EXPOSE 80

